# Generated by Django 4.2.8 on 2026-01-30 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'DNI debe ser de 8 dígitos')])),
                ('celular', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Celular debe ser de 9 dígitos')])),
                ('referencia', models.TextField(blank=True, help_text='Numeración o referencia de ubicación', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='billing_app.distrito')),
            ],
            options={
                'unique_together': {('distrito', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SerieCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo')], max_length=10, unique=True)),
                ('serie', models.CharField(max_length=4)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='billing_app.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(max_length=10)),
                ('serie_numero', models.CharField(max_length=20)),
                ('detalles', models.TextField(help_text='Detalle de meses pagados')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_cobranza', models.IntegerField(help_text='Día del mes para cobrar (1-31)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='billing_app.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.plan')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='billing_app.via'),
        ),
    ]
