# Generated by Django 4.2.8 on 2026-01-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_ordentecnicaconcepto_servicio_plan_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pdf_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.DateField(help_text='Primer día del mes pagado')),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(help_text='Ej: Mes completo, 15 días, etc', max_length=200)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing_app.pago')),
                ('plan_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.clienteplan')),
            ],
        ),
    ]
