# Generated by Django 4.2.8 on 2026-01-31 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_pago_pdf_comprobante_pagodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodetalle',
            name='descripcion',
            field=models.CharField(help_text='Ej: Mes completo, 15 días, OT, etc', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='periodo_mes',
            field=models.DateField(blank=True, help_text='Primer día del mes pagado', null=True),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='plan_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.clienteplan'),
        ),
        migrations.CreateModel(
            name='OrdenTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tecnicas', to='billing_app.cliente')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_app.ordentecnicaconcepto')),
            ],
        ),
        migrations.AddField(
            model_name='pagodetalle',
            name='ot_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.ordentecnica'),
        ),
    ]
