# Generated by Django 4.2.8 on 2026-01-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_alter_pagodetalle_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_host', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('puerto_api', models.IntegerField(default=8728)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ip_asignada',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password_pppoe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_conexion',
            field=models.CharField(choices=[('PPPOE', 'PPPoE'), ('DHCP', 'DHCP'), ('STATIC', 'Estática')], default='PPPOE', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_pppoe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentecnicaconcepto',
            name='categoria',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('AVERIAS', 'Averías'), ('CORTES', 'Cortes')], default='AVERIAS', max_length=20),
        ),
        migrations.AddField(
            model_name='via',
            name='tipo',
            field=models.CharField(choices=[('AVENIDA', 'Avenida'), ('JIRON', 'Jirón'), ('CALLE', 'Calle'), ('PASAJE', 'Pasaje')], default='CALLE', max_length=15),
        ),
        migrations.CreateModel(
            name='IPStaticaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('en_uso', models.BooleanField(default=False)),
                ('mikrotik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.mikrotikconfig')),
            ],
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rango', models.CharField(help_text='Ej: 192.168.10.2-192.168.10.254', max_length=100)),
                ('mikrotik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='billing_app.mikrotikconfig')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='mikrotik_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.mikrotikconfig'),
        ),
    ]
