# Generated by Django 6.0.1 on 2026-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_tecnico_ordentecnica_tecnico_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentecnica',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el técnico realizó/finalizó el trabajo', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password_pppoe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mikrotikconfig',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
