# Generated by Django 6.0.1 on 2026-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0013_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteplan',
            name='activo',
            field=models.BooleanField(
                default=True,
                help_text='Indica si el plan está activo para el cliente'
            ),
        ),
    ]
