# Generated by Django 6.0.1 on 2026-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0014_clienteplan_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentecnicaconcepto',
            name='categoria',
            field=models.CharField(choices=[('INSTALACION', 'Instalación'), ('AVERIAS', 'Averías'), ('CORTES', 'Cortes'), ('RECONEXION', 'Reconexión')], default='AVERIAS', max_length=20),
        ),
    ]
