# Generated by Django 6.0.1 on 2026-02-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0015_alter_ordentecnicaconcepto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentecnica',
            name='fecha_asistencia',
            field=models.DateField(blank=True, help_text='Fecha de instalación o asistencia', null=True),
        ),
    ]
