# Generated by Django 6.0.1 on 2026-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0017_set_clienteplan_activo_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteplan',
            name='activo',
            field=models.BooleanField(default=False, help_text='Indica si el plan está activo para el cliente'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el plan está activo para el cliente'),
        ),
    ]
