# Generated by Django 6.0.1 on 2026-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0018_alter_clienteplan_activo_alter_tecnico_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_instalacion',
            field=models.DateField(blank=True, help_text='Fecha de instalacion del servicio', null=True),
        ),
    ]
