# Generated by Django 4.2.8 on 2026-01-24 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaNap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('puertos_capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('puertos_libres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'verbose_name': 'Caja NAP',
                'verbose_name_plural': 'Cajas NAP',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni_ruc', models.CharField(max_length=15, unique=True)),
                ('nombres_completos', models.CharField(max_length=200)),
                ('numero_casa', models.CharField(max_length=10)),
                ('mz_lote_int', models.CharField(blank=True, max_length=50, null=True)),
                ('telf', models.CharField(max_length=20)),
                ('estado_cliente', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Retirado', 'Retirado')], default='Activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombres_completos'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FibraTramo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('hilos_totales', models.IntegerField(choices=[(12, '12'), (24, '24'), (48, '48'), (96, '96'), (144, '144')])),
                ('tipo_fibra', models.CharField(max_length=50)),
                ('lat_inicio', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon_inicio', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat_fin', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon_fin', models.DecimalField(decimal_places=8, max_digits=11)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tramo de Fibra',
                'verbose_name_plural': 'Tramos de Fibra',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemSeriado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Almacen', 'Almacén'), ('Instalado', 'Instalado'), ('Taller', 'Taller')], default='Almacen', max_length=20)),
            ],
            options={
                'verbose_name': 'Item Seriado',
                'verbose_name_plural': 'Items Seriados',
            },
        ),
        migrations.CreateModel(
            name='MaterialCatalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('es_seriado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Material Catálogo',
                'verbose_name_plural': 'Materiales Catálogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('rol', models.CharField(choices=[('Tecnico', 'Técnico'), ('Admin', 'Administrador'), ('Soporte', 'Soporte')], max_length=30)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['nombres_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='PlanInternet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=50, unique=True)),
                ('mbps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Plan Internet',
                'verbose_name_plural': 'Planes Internet',
                'ordering': ['mbps'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='isp_app.distrito')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['distrito', 'nombre'],
                'unique_together': {('distrito', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('km_actual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('soat_vence', models.DateField()),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_via', models.CharField(choices=[('Avenida', 'Avenida'), ('Jiron', 'Jirón'), ('Calle', 'Calle'), ('Pasaje', 'Pasaje'), ('Carretera', 'Carretera')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='isp_app.sector')),
            ],
            options={
                'verbose_name': 'Vía',
                'verbose_name_plural': 'Vías',
                'ordering': ['sector', 'tipo_via', 'nombre'],
                'unique_together': {('sector', 'tipo_via', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ServicioActivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puerto_nap_nro', models.IntegerField()),
                ('potencia_dbm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lat_instalacion', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon_instalacion', models.DecimalField(decimal_places=8, max_digits=11)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_activos', to='isp_app.cliente')),
                ('nap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='isp_app.cajanap')),
                ('onu_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='isp_app.itemseriado')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isp_app.planinternet')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_instalados', to='isp_app.personal')),
                ('via_real_instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_instalados', to='isp_app.via')),
            ],
            options={
                'verbose_name': 'Servicio Activo',
                'verbose_name_plural': 'Servicios Activos',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_municipal', models.CharField(max_length=10)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('cert_digital_path', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='isp_app.via')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre_sede'],
            },
        ),
        migrations.CreateModel(
            name='PersonalSaludDotacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_sanguineo', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('sctr_nro', models.CharField(max_length=50)),
                ('talla_polo_calzado', models.CharField(max_length=20)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salud_dotacion', to='isp_app.personal')),
            ],
            options={
                'verbose_name': 'Salud y Dotación Personal',
                'verbose_name_plural': 'Salud y Dotación Personal',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='isp_app.sede'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='isp_app.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mufa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Troncal', 'Troncal'), ('Distribucion', 'Distribución')], max_length=30)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mufas', to='isp_app.via')),
            ],
            options={
                'verbose_name': 'Mufa',
                'verbose_name_plural': 'Mufas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='isp_app.personal')),
            ],
            options={
                'verbose_name': 'Log Auditoría',
                'verbose_name_plural': 'Logs Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='itemseriado',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_seriados', to='isp_app.materialcatalogo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='isp_app.via'),
        ),
        migrations.AddField(
            model_name='cajanap',
            name='mufa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_nap', to='isp_app.mufa'),
        ),
        migrations.AddField(
            model_name='cajanap',
            name='via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_nap', to='isp_app.via'),
        ),
        migrations.CreateModel(
            name='ServidorMikrotik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_host', models.GenericIPAddressField()),
                ('puerto_api', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores_mikrotik', to='isp_app.sede')),
            ],
            options={
                'verbose_name': 'Servidor Mikrotik',
                'verbose_name_plural': 'Servidores Mikrotik',
                'unique_together': {('sede', 'ip_host')},
            },
        ),
        migrations.CreateModel(
            name='EquipoOltEdfa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('ip_gestion', models.GenericIPAddressField()),
                ('tipo_equipo', models.CharField(choices=[('OLT', 'OLT'), ('EDFA', 'EDFA')], max_length=20)),
                ('puertos_pon_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_olt_edfa', to='isp_app.sede')),
            ],
            options={
                'verbose_name': 'Equipo OLT/EDFA',
                'verbose_name_plural': 'Equipos OLT/EDFA',
                'unique_together': {('sede', 'nombre')},
            },
        ),
    ]
